# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PortariaReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PortariaReact
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 5.11.0'

  target 'PortariaReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PortariaReact-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PortariaReact-tvOS

  target 'PortariaReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
